In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [4]:
#列表复制创建矩阵向量
my_list = [1,2,3,4,5]
second_list = [[1,2,3],[4,5],[6,7]]
c = np.array(my_list)
d = np.array(second_list) 
print(c)
print(d)

[1 2 3 4 5]
[list([1, 2, 3]) list([4, 5]) list([6, 7])]


In [5]:
#使用内置函数创建矩阵向量

#arange函数，使用方法类似range
vector_1 = np.arange(10)
vector_2 = np.arange(0,11,2)

#zeros函数，创建元素为0的矩阵向量
vector_z1 = np.zeros(7)
vector_z2 = np.zeros((7,6)) #创建矩阵注意双层括号

#ones函数
vector_o1 = np.ones(7)
vector_o2 = np.ones((7,6)) #创建矩阵注意双层括号

print(vector_1)
print(vector_2)
print(vector_z1)
print(vector_z2)
print(vector_o1)
print(vector_o2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]
[0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [6]:
#linspace函数，在两个值之间创建等间隔的数个点
lin_arr = np.linspace(1,3,15)
print(lin_arr)

[1.         1.14285714 1.28571429 1.42857143 1.57142857 1.71428571
 1.85714286 2.         2.14285714 2.28571429 2.42857143 2.57142857
 2.71428571 2.85714286 3.        ]


In [7]:
#eye函数，创建单位矩阵(E)
my_matrx = np.eye(6)
print(my_matrx)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [8]:
#rand(),randn(),randint(),生成随机数组成的矩阵
my_rand = np.random.rand(5,4)
#以标准正态分布或高斯分布产生随机数
my_randn = np.random.randn(7)
my_randn1 = np.random.randn(7,5)
#randint:在一个取值区间内随机生成几个数
my_randint = np.random.randint(1,10,10)

print(my_rand)
print(my_randn)
print(my_randn1)
print(my_randint)

[[0.2813701  0.62243787 0.21800322 0.41547542]
 [0.41552824 0.84330162 0.89019327 0.71143913]
 [0.88786321 0.01283196 0.45702968 0.750603  ]
 [0.2487925  0.57781083 0.53349429 0.59084897]
 [0.77671373 0.33268635 0.07408498 0.61715115]]
[-1.42912097  0.87347934  0.18111063 -1.6698372   2.07160968 -0.10829775
 -0.11901153]
[[-1.07868204 -0.64775246 -1.38256681 -1.28834279  0.03077504]
 [ 0.28729889 -0.02220295 -1.55057006 -1.86283564  0.10447328]
 [-0.01661651 -0.68699003  0.38122342 -1.13322567  0.21473868]
 [ 0.52529187  1.58843132 -0.03269845 -0.82269908 -0.57714008]
 [ 0.03832453  0.52173395  1.33314066  0.20993298 -2.06971569]
 [ 0.43703583 -0.75585153 -0.33692395 -1.14506221  0.49661782]
 [-0.47836922 -1.7046346   1.75534239 -0.27895994 -2.82668803]]
[8 4 5 2 2 5 4 7 7 1]


In [9]:
a = np.array([[1,2,3],[4,5,6]])
#获取矩阵的维度
print(a.shape)
#resharp函数，可改变矩阵的维度
b = a.reshape(3,2)
print(b)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [10]:
a = np.array([[1,2],[3,4],[11,12]])
b = np.array([[5,6,13],[7,8,14]])
c = np.array([[1,2,13],[3,4,25],[11,12,23]])
d = np.array([[5,6,2],[7,8,29],[13,14,15]])

matrix_a = np.matrix(a)         # (3,2)
matrix_b = np.matrix(b)         # (2,3)
matrix_c = np.matrix(c)         # (3,3)
matrix_d = np.matrix(d)         # (3,3)

print(type(a),type(matrix_a))  # <class 'numpy.ndarray'> <class 'numpy.matrixlib.defmatrix.matrix'>
mat_a = np.mat(a)
print(type(a),type(matrix_a))  # <class 'numpy.ndarray'> <class 'numpy.matrixlib.defmatrix.matrix'>


<class 'numpy.ndarray'> <class 'numpy.matrix'>
<class 'numpy.ndarray'> <class 'numpy.matrix'>


In [11]:
'''
# 1) matrix multiplication
矩阵乘法： (m,n) x (n,p) --> (m,p)    # 矩阵乘法运算前提：矩阵1的列=矩阵2的行
3种用法： np.dot(matrix_a, matrix_b) == matrix_a @ matrix_b == matrix_a * matrix_b
'''
method_1 = matrix_a @ matrix_b
method_2 = np.dot(matrix_a, matrix_b)

print(method_1)
#[[ 19  22  41]
# [ 43  50  95]
# [139 162 311]]
print(method_2 == method_1)
#[[ True  True  True]
# [ True  True  True]
# [ True  True  True]]
print(matrix_c * matrix_d == matrix_c @ matrix_d)
#[[ True  True  True]
# [ True  True  True]
# [ True  True  True]]


[[ 19  22  41]
 [ 43  50  95]
 [139 162 311]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [12]:

'''
# 2） element-wise product ： 矩阵对应元素相乘
1种用法：np.multiply(matrix_c, matrix_d)
对于nd.array()类型而言，数组 arrA * arrB 只能element-wise produt(对应元素相乘) 
'''
print(matrix_c, matrix_d, sep='\n')
#[[ 1  2 13]
# [ 3  4 25]
# [11 12 23]]
#[[ 5  6  2]
# [ 7  8 29]
# [13 14 15]]

method_1 = np.multiply(matrix_c, matrix_d)      # 对应位置元素相乘

print(method_1)
#[[  5  12  26]
# [ 21  32 725]
# [143 168 345]]

[[ 1  2 13]
 [ 3  4 25]
 [11 12 23]]
[[ 5  6  2]
 [ 7  8 29]
 [13 14 15]]
[[  5  12  26]
 [ 21  32 725]
 [143 168 345]]


In [13]:
import matplotlib.pyplot as plt

#图形输入值
input_values = [1,2,3,4,5]
#图形输出值
squares = [1,4,9,16,25]

#plot根据列表绘制出有意义的图形，linewidth是图形线宽，可省略
plt.plot(input_values,squares,linewidth=5)
#设置图标标题
plt.title("Square Numbers",fontsize = 24)
#设置坐标轴标签
plt.xlabel("Value",fontsize = 14)
plt.ylabel("Square of Value",fontsize = 14)
#设置刻度标记的大小
plt.tick_params(axis='both',labelsize = 14)
#打开matplotlib查看器，并显示绘制图形
plt.show()

<Figure size 640x480 with 1 Axes>

In [14]:
#squeeze 函数：从数组的形状中删除单维度条目，即把shape中为1的维度去掉
'''
    用法：numpy.squeeze(a,axis = None)
    1）a表示输入的数组；
    2）axis用于指定需要删除的维度，但是指定的维度必须为单维度，否则将会报错；
    3）axis的取值可为None 或 int 或 tuple of ints, 可选。若axis为空，则删除所有单维度的条目；
    4）返回值：数组；
    5) 不会修改原数组。

'''
a = np.array([[[1,2,3,4,5,6]]])
print(a)
a = np.squeeze(a)
print(a)

[[[1 2 3 4 5 6]]]
[1 2 3 4 5 6]


In [15]:
a = np.array([5,6,1,23,3])
np.argmax(a)

3

In [6]:
def objective_function(individual):
    distance = 0
    for index in range(100):
        distance += np.sqrt(((individual - data[index]) ** 2).sum(axis=0))  # subtract 减
    return distance


In [7]:
data = np.loadtxt("C:\\Users\\User\\PycharmProjects\\GAK-means\\uniform_location_demo.txt", delimiter=',')

In [15]:
objective_function(np.array([100,100]))


19117.147966226443

In [12]:
np.sqrt(((np.array([100,100]) - np.array([150,150])) ** 2).sum(axis=0))

70.71067811865476

In [5]:
#排序
# a = np.array([[1,2,1],[2,4,2],[5,3,3],[5,7,4]])
a = np.array([[1,2,5],[2,4,3],[5,3,1],[5,7,8]])

print(a)
a = a[a[:,2].argsort()]
print(a)

[[1 2 5]
 [2 4 3]
 [5 3 1]
 [5 7 8]]
[[5 3 1]
 [2 4 3]
 [1 2 5]
 [5 7 8]]


In [11]:
Y = np.zeros((100,1))
#print(Y)
for index in range(100):
     Y[index] = objective_function(ga.X[index])
     # print(Y)
print(Y)
# o = np.hstack(ga.X,Y)
# o = o[o[:,2].argsort()]
# print(o)


NameError: name 'ga' is not defined

In [14]:
def objective_function(x):
    return max(5e-4*(1-x),4.75e-4*x)

In [18]:
objective_function(np.array([1,2,3,4]))


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [14]:
x = np.array([[1,2],[2,4]])
y = np.array([[0],[1]])
o = np.hstack([x,np.zeros(2,1)])
#o = np.concatenate([x,y],axis=1)
print(o)

TypeError: data type not understood

In [10]:
x = np.array([0,1,2])
print(x)
x = np.expand_dims(x,axis=1)
print(x)


[0 1 2]
[[0]
 [1]
 [2]]


In [12]:
print(e in [0,1,2,3])

NameError: name 'e' is not defined

In [19]:
np.full((4,1),100)

array([[100],
       [100],
       [100],
       [100]])

In [2]:
rewards = [-2, -2, -2, 10, 1, -1, 0]

In [4]:
rewards = np.array(rewards).reshape((-1,1))
print(rewards)

[[-2]
 [-2]
 [-2]
 [10]
 [ 1]
 [-1]
 [ 0]]
